spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/product
    username: admin
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8001
