eureka:
  instance:
    hostname: eurekaserver
    client:
      serviceUrl:
        defaultZone: http://eurekaserver:8761/eureka
spring:
  cloud:
    config:
      overrideSystemProperties: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
