eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME}
    client:
      serviceUrl:
        defaultZone: http://v${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka
spring:
  cloud:
    config:
      overrideSystemProperties: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
