eureka:
  instance:
    hostname: eureka-server
    client:
      serviceUrl:
        defaultZone: http://eureka-server:8761/eureka
spring:
  cloud:
    config:
      overrideSystemProperties: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
