spring:
  datasource:
    name: inventory
    generate-unique-name: false
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
server:
  port: 8002
